name: Validar nombre de rama

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Validar nombre de rama
        run: |
          echo "Nombre de rama: ${{ github.head_ref }}"
          if [[ ! "${{ github.head_ref }}" =~ ^(feature|bugfix|hotfix|refactor|chore|test|experiment)/.+$ ]]; then
            echo "::error ::❌ Nombre de rama inválido: '${{ github.head_ref }}'"
            echo "::error ::Debe comenzar con: feature/, bugfix/, hotfix/, refactor/, chore/, test/, experiment/"
            exit 1
          fi
